### ISSUE TITLE
현재 신형으로 수정 중입니다.

### ISSUE THREAD

**Issue by 2du** [openNAMU/openNAMU-Tool-Namu_JSON#4]

**Comment by SakuraSuFl** [comment]
리소스 많이 잡아먹는건 아직 어쩔수 없는 건가요?

**Comment by 2du** [comment]
@SakuraSuFl 그거는 원본 자체가 10기가이다보니 이것도 덜 잡아먹게 노력한 겁니다

원래는 최소 램이 16기가는 되야 어찌저찌 됩니다

**Comment by CheongWol2** [comment]
혹시 편집 시간이 없는 경우 해당 DB를 변환한 날짜로 자동으로 변경되게는 하실 수 있으신가요?

**Comment by 2du** [comment]
@CheongWol2 그 기능은 이번에 수정하면서 이미 들어가 있습니다

**Comment by CheongWol2** [comment]
현재 편집 로그가 비어있어 문서를 삭제하면 되돌리기가 안 됩니다. 혹시 문서의 데이터를 첫 번째 사용자가 모두 기여한 것으로 바뀌게 개선해주실 수 있으신가요?

**Comment by 2du** [comment]
@CheongWol2 현재는 마지막 리비전에만 문서 내용을 넣어놨으니 마지막 문서로 되돌리세요

그리고 전체 리비전에 문서 내용을 넣으면 용량이 왕창 늘어나게 되어버려서 안됩니다

**Comment by 2du** [comment]
아 맞다 다 했는데 이슈를 안 닫았네
