### ISSUE TITLE
이거 버근가요?

### ISSUE THREAD

**Issue by SakuraSuFl** [openNAMU/openNAMU-Tool-Namu_JSON#9]
제가 나무위키가 아닌 알파위키 덤프파일을 써서 그런진 몰라도
임시데이터 저장하는것 까진 문제가 없는데 변환하는 과정부터 문제가 생깁니다.
Traceback (most recent call last):
  File "D:\DBtest\namujson.py", line 171, in <module>
    mainprocess(dictdata)
  File "D:\DBtest\namujson.py", line 135, in mainprocess
    curs.execute(db_change("insert into data (title, data) values (?, ?)"), [title, text])
NameError: name 'db_change' is not defined
단순히 호환이 안되서 그러는건가요 아님 버그인가요?

**Comment by 2du** [comment]
버그네요

**Comment by 2du** [comment]
수정 완료
